//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//

#ifndef RIAPS_CORE_DSO_H
#define RIAPS_CORE_DSO_H

#include "componentmodel/r_componentbase.h"
#include "ReqAddr.capnp.h"
#include "RepAddr.capnp.h"

// Name of the ports from the model file
#define PORT_REP_CONTRACTADDR "contractAddr"
#define PORT_TIMER_FINALIZER "finalizer"

namespace transactiveenergy {
   namespace components {
      
      class DSOBase : public riaps::ComponentBase {
         
         public:
         DSOBase(_component_conf &config, riaps::Actor &actor);
         
         virtual void OnContractAddr(const ReqAddr::Reader &message,
         riaps::ports::PortBase *port)=0;
         
         virtual bool SendContractAddr(capnp::MallocMessageBuilder& messageBuilder,
         RepAddr::Builder& message);
         
         virtual void OnFinalizer(riaps::ports::PortBase *port)=0;
         
         virtual ~DSOBase();
         protected:
         virtual void DispatchMessage(capnp::FlatArrayMessageReader* capnpreader, riaps::ports::PortBase *port,std::shared_ptr<riaps::MessageParams> params=nullptr );
         virtual void DispatchInsideMessage(zmsg_t* zmsg, riaps::ports::PortBase* port);
      };
   }
}
#endif //RIAPS_CORE_DSO_H
