//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#ifndef RIAPS_FW_RECORDER_H
#define RIAPS_FW_RECORDER_H

#include "RecorderBase.h"

namespace transactiveenergy {
   namespace components {
      
      class Recorder : public RecorderBase {
         
         public:
         
         Recorder(_component_conf &config, riaps::Actor &actor);
         
         
         virtual void OnPoller(riaps::ports::PortBase *port);
         
         void OnGroupMessage(const riaps::groups::GroupId& groupId, capnp::FlatArrayMessageReader& capnpreader, riaps::ports::PortBase* port);
         
         virtual ~Recorder();
         
      };
   }
}

extern "C" riaps::ComponentBase* create_component(_component_conf&, riaps::Actor& actor);
extern "C" void destroy_component(riaps::ComponentBase*);


#endif //RIAPS_FW_RECORDER_H
