//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#ifndef RIAPS_FW_SOLVER_H
#define RIAPS_FW_SOLVER_H

#include "SolverBase.h"

namespace transactiveenergy {
   namespace components {
      
      class Solver : public SolverBase {
         
         public:
         
         Solver(_component_conf &config, riaps::Actor &actor);
         
         
         void OnGroupMessage(const riaps::groups::GroupId& groupId, capnp::FlatArrayMessageReader& capnpreader, riaps::ports::PortBase* port);
         
         virtual ~Solver();
         
      };
   }
}

extern "C" riaps::ComponentBase* create_component(_component_conf&, riaps::Actor& actor);
extern "C" void destroy_component(riaps::ComponentBase*);


#endif //RIAPS_FW_SOLVER_H
