//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//

#ifndef RIAPS_CORE_TRADER_H
#define RIAPS_CORE_TRADER_H

#include "componentmodel/r_componentbase.h"
#include "ReqAddr.capnp.h"
#include "RepAddr.capnp.h"

// Name of the ports from the model file
#define PORT_REQ_CONTRACTADDR "contractAddr"
#define PORT_TIMER_POLLER "poller"
#define PORT_TIMER_POST "post"

namespace transactiveenergy {
   namespace components {
      
      class TraderBase : public riaps::ComponentBase {
         
         public:
         TraderBase(_component_conf &config, riaps::Actor &actor);
         
         bool SendContractAddr(capnp::MallocMessageBuilder&    messageBuilder,
         ReqAddr::Builder& message);
         
         bool RecvContractAddr(RepAddr::Reader &message);
         
         virtual void OnPoller(riaps::ports::PortBase *port)=0;
         
         virtual void OnPost(riaps::ports::PortBase *port)=0;
         
         virtual ~TraderBase();
         protected:
         virtual void DispatchMessage(capnp::FlatArrayMessageReader* capnpreader, riaps::ports::PortBase *port,std::shared_ptr<riaps::MessageParams> params=nullptr );
         virtual void DispatchInsideMessage(zmsg_t* zmsg, riaps::ports::PortBase* port);
      };
   }
}
#endif //RIAPS_CORE_TRADER_H
