//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#include <RecorderBase.h>

namespace transactiveenergy {
   namespace components {
      
      RecorderBase::RecorderBase(_component_conf &config, riaps::Actor &actor) : ComponentBase(config, actor) {
         
      }
      
      void RecorderBase::DispatchMessage(capnp::FlatArrayMessageReader* capnpreader, riaps::ports::PortBase *port,std::shared_ptr<riaps::MessageParams> params) {
         auto portName = port->GetPortName();
         
         if (portName == PORT_TIMER_POLLER) {
            OnPoller(port);
         }
         
      }
      
      void RecorderBase::DispatchInsideMessage(zmsg_t* zmsg, riaps::ports::PortBase* port) {
         //empty the header
      }
      
      bool RecorderBase::SendContractAddr(capnp::MallocMessageBuilder &messageBuilder,
      ReqAddr::Builder &message) {
         //std::cout<< "RecorderBase::SendContractAddr()"<< std::endl;
         return SendMessageOnPort(messageBuilder, PORT_REQ_CONTRACTADDR);
      }
      
      bool RecorderBase::RecvContractAddr(RepAddr::Reader &message) {
         //std::cout<< "RecorderBase::RecvContractAddr()"<< std::endl;
         auto port = GetRequestPortByName(PORT_REQ_CONTRACTADDR);
         if (port == NULL) return false;
         
         capnp::FlatArrayMessageReader* messageReader;
         
         if (port->Recv(&messageReader)){
            message = messageReader->getRoot<RepAddr>();
            return true;
         }
         return false;
      }
      
      RecorderBase::~RecorderBase() {
         
      }
   }
}
